sudo: false
language: ruby
rvm:
- 2.5.0
before_install: gem install bundler -v 1.16.1
env:
  global:
    secure: A59RFXDob3tLwj4h0HH+Nj9EQRW8kRE0QyDCFWSdazr3uudLz000rCVpgzuzK1DbrT1R8lHCwxKcnzyQHOEWTyV0kCd2I0CEU2ri4TAgNlJyvCfHEaW7CcSKFUILEpM3FQKxFgGAE0j/a0UITKhrdxErH6yP/PGMSZLIQ9lMvWGhAGtj8vS/qtWjW1ckZ/jEYZS8MM1VUKw20ToNwsMW63OAHax1hbow/29x/G/1WE2be366CNI2r/eqnhazVfoJ0l2nOdbMNwOdy1aq0Qzqr82NpleRAM/E0hSjTOh1opDA4ZoMbSQP34Oyy9jaaeM3oazAX4QdfWziD9+6zuLFOEP5UEpSosxG6QQmk9KwAUIg9JFd45GqZ/dIOu0SSfTvcCTIS0FMthRkLLpg+p4/ZRu8vCvSSc/zxE2dMrBWjmrHGPk31TUolZ8RoeKBakvc1i2073l5qXcm0ISyShgMlMKSvLB7s5kpzxRf2UpfAbM+aFggY35SzYX4T5mNtw7B26Co1Onhn3Q/x32YgJyYusSSXC5ZkRLHYsSLQNCYNh4F3Ze87BL0Z/77GpFU4/hXPsYe+XfiPXmjKai/ggLoz+ysINu44Ue30cJCXQSObBLVHoQh1gcdehnmm3MXGnDTeLpxexdVovEATJ6FlK95yyB529jt+TaqQ2eGNSuHYzM=
